config/routes.rb
Misaleanegager::Application.routes.draw do
  resources :contacts

  resources :lookups

  resources :misales

  resources :challenges

  resources :about

  match '/fetan/toggle' => 'application#fetan'
  
  match '/misales/:id/fbpost' => 'misales#fbpost', :as => :fbpost_misale
  
  match '/' => 'misales#home'
  
  match '/fbcanvas' => 'application#fbcanvas'
  
  match '/oqpi' => 'application#tweet'

end

app/models/lookup.rb
class Lookup < ActiveRecord::Base
end

app/controllers/lookups_controller.rb
class LookupsController < ApplicationController
  # GET /lookups
  # GET /lookups.xml
  def index
    @lookups = Lookup.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @lookups }
    end
  end

  # GET /lookups/1
  # GET /lookups/1.xml
  def show
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @lookup }
    end
  end

  # GET /lookups/new
  # GET /lookups/new.xml
  def new
    @lookup = Lookup.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @lookup }
    end
  end

  # GET /lookups/1/edit
  def edit
    @lookup = Lookup.find(params[:id])
  end

  # POST /lookups
  # POST /lookups.xml
  def create
    @lookup = Lookup.new(params[:lookup])

    respond_to do |format|
      if @lookup.save
        format.html { redirect_to(@lookup, :notice => 'Lookup was successfully created.') }
        format.xml  { render :xml => @lookup, :status => :created, :location => @lookup }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @lookup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /lookups/1
  # PUT /lookups/1.xml
  def update
    @lookup = Lookup.find(params[:id])

    respond_to do |format|
      if @lookup.update_attributes(params[:lookup])
        format.html { redirect_to(@lookup, :notice => 'Lookup was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @lookup.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /lookups/1
  # DELETE /lookups/1.xml
  def destroy
    @lookup = Lookup.find(params[:id])
    @lookup.destroy

    respond_to do |format|
      format.html { redirect_to(lookups_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/lookups_helper.rb
module LookupsHelper
end

app/views/lookups/_form.html.erb
<%= simple_form_for(@lookup) do |f| %>
  <%= f.error_notification %>

  <div class="inputs">
    <%= f.input :key %>
    <%= f.input :value %>
  </div>

  <div class="actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/lookups/edit.html.erb
<h1>Editing lookup</h1>

<%= render 'form' %>

<%= link_to 'Show', @lookup %> |
<%= link_to 'Back', lookups_path %>

app/views/lookups/index.html.erb
<h1>Listing lookups</h1>

<table>
  <tr>
    <th>Key</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @lookups.each do |lookup| %>
  <tr>
    <td><%= lookup.key %></td>
    <td><%= lookup.value %></td>
    <td><%= link_to 'Show', lookup %></td>
    <td><%= link_to 'Edit', edit_lookup_path(lookup) %></td>
    <td><%= link_to 'Destroy', lookup, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Lookup', new_lookup_path %>

app/views/lookups/new.html.erb
<h1>New lookup</h1>

<%= render 'form' %>

<%= link_to 'Back', lookups_path %>

app/views/lookups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Key:</b>
  <%= @lookup.key %>
</p>

<p>
  <b>Value:</b>
  <%= @lookup.value %>
</p>


<%= link_to 'Edit', edit_lookup_path(@lookup) %> |
<%= link_to 'Back', lookups_path %>