config/routes.rb
Misaleanegager::Application.routes.draw do
  resources :contacts

  resources :lookups

  resources :misales

  resources :challenges

  resources :about

  match '/fetan/toggle' => 'application#fetan'
  
  match '/misales/:id/fbpost' => 'misales#fbpost', :as => :fbpost_misale
  
  match '/' => 'misales#home'
  
  match '/fbcanvas' => 'application#fbcanvas'
  
  match '/oqpi' => 'application#tweet'

end

app/models/misale.rb
class Misale < ActiveRecord::Base
  has_many :comments
  has_many :categorizations
  has_many :chanllenges, :through => :categorizations
  has_many :answers, :through => :categorizations
  
  validates_presence_of :head, :tail #, :comments
  
  accepts_nested_attributes_for :comments, :reject_if => lambda { |a| a[:comment].blank? }, :allow_destroy => true

  
  def name
    "#{self.head} #{self.tail}"
  end
  
  def self.search(search)  
    if search  
      find(:all, :conditions => ['head LIKE ? OR tail LIKE ?', "%#{search}%", "%#{search}%"])  
    else  
      find(:all)  
    end  
  end  
end

app/controllers/misales_controller.rb
class MisalesController < ApplicationController
  # GET /misales
  # GET /misales.xml
  def index
    @page_size = params[:size].nil? ? 1 : params[:size].to_i
    @fetan = session[:fetan].nil? || session[:fetan]
    @page = params[:page] == 'rand' || params[:page].nil? ? rand(Misale.all.count).to_i : params[:page].to_i 
    @page = 1 if @page < 1
    @misales = Misale.search(params[:search]).paginate(:per_page => @page_size, :page => @page)
    @admin = !params[:admin].nil?
    
    
    # for the new once create a comment object
    for misale in @misales do
      misale.comments.build
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @misales }
    end
  end

  # GET /misales/1
  # GET /misales/1.xml
  def show
    redirect_to :action => 'index', :page => params[:id]
  end

  # GET /misales/new
  # GET /misales/new.xml
  def new
    @misale = Misale.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @misale }
    end
  end

  # GET /misales/1/edit
  def edit
    @misale = Misale.find(params[:id])
  end

  # POST /misales
  # POST /misales.xml
  def create
    @misale = Misale.new(params[:misale])

    respond_to do |format|
      if @misale.save
        format.html { redirect_to(@misale, :notice => 'Misale was successfully created.') }
        format.xml  { render :xml => @misale, :status => :created, :location => @misale }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @misale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /misales/1
  # PUT /misales/1.xml
  def update
    @misale = Misale.find(params[:id])
    
    # Create if contact is not found 
    contact = Contact.find_or_create_by_nickname_and_email_and_phone_and_fbuid(params[:contact]) 
    
    # Hack - Tweak contact id with the one fetched or created above.
    unless params[:misale][:comments_attributes].nil? then
      params[:misale][:comments_attributes].each_value do |comment_value|
        if contact.new_record? then #invalid contact info provided, remove comment so it won't be saved
          comment_value[:comment] = nil
        elsif comment_value.has_key? :contact_id then
          comment_value[:contact_id] = contact.id.to_s
        end
      end      
    end
    
    respond_to do |format|
      if @misale.update_attributes(params[:misale])
        format.html { redirect_to(@misale, :notice => 'Misale was successfully updated.') }
        format.xml  { head :ok }
      else
        # TODO - once we have admin/non-admin users defined, redirect based on rights.
        format.html { render :action => "show" }
        format.xml  { render :xml => @misale.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /misales/1
  # DELETE /misales/1.xml
  def destroy
    @misale = Misale.find(params[:id])
    @misale.destroy

    respond_to do |format|
      format.html { redirect_to(misales_url) }
      format.xml  { head :ok }
    end
  end
  
  def fbpost
    @misale = Misale.find(params[:id])

    @misale.ye = @misale.ye.nil? ? 1 : 1 + @misale.ye
    @misale.save
    
    render  :partial => '/misales/unload'
  end
    
  def home
    respond_to do |format|
      format.html # index.html.erb
      #format.xml  { render :xml => @misales }
    end
  end
end

app/helpers/misales_helper.rb
module MisalesHelper
end

app/views/misales/_answers.html.erb
<div id="answers_<%= misale.id %>" misale='<%= misale.head %>' class='<%= @fetan ? "hidden" : "" %>'>
	<% for categorization in misale.categorizations %>
		<%#<div class='section_header'><%= ApplicationHelper.get_value(:responses, :responses)  >:</div>%>
		<div class='answers'>
		<% for answer in categorization.answers %>
			<%= render :partial => 'contacts/user', :locals => {:u => answer.contact, :d => answer.created_at } %>
			<div class="comment-bubble">
				<%= misale.head %>&nbsp;<u><%= answer.response %></u>
				<div class="comment-bubble-arrow"></div>
			</div>
		<% end %>
		</div>
	<% end %>
</div>

app/views/misales/_comment.html.erb
<div id='comments_<%= misale.id %>' class='<%= @fetan ? "fetanHidden" : "" %>' >
	<%#<div class='section_header <%= @fetan ? "fetanHidden" : "" % >'>< %= ApplicationHelper.get_value(:comments, :comments) % >:</div>%>
	<div class='comments'>	
		<%= simple_form_for(misale) do |f| %>
			<% f.fields_for :comments do |builder| %>
				<% if builder.object.new_record? %>
				    <br/>
					<div style='padding-left:110px;'>
	                    <%= builder.hidden_field :contact_id %>
	                    &nbsp;&nbsp;&nbsp;&nbsp;Your comment
	                    <br/>
	                    <img style='float:left'  fbKey='avatar'/>
	                    <%= builder.input :comment, :label => false, :input_html => { :rows => 4, :class => 'inputfield' } %>
	                    <%= render 'contacts/contact', :f => builder %>
						<div class="actions">
							<%= f.button :submit, :value => 'submit', :class => 'actionButton' %>
						</div>
					</div>
				<% else %>
				    <div class='comment' class='<%= @fetan ? "fetan" : "" %>'>
				    	<%= render :partial => 'contacts/user', :locals => {:u => builder.object.contact, :d => builder.object.created_at } %>
						<div class="comment-bubble">
							<%= builder.object.comment %>
						  <div class="comment-bubble-arrow"></div>
						</div>
					</div>
				<% end %>
			<% end %>
		<% end %>
	</div>

</div>

app/views/misales/_error.html.erb
<% if misale.errors.any? %>
	<div id="error_explanation">
	  <h2><%= pluralize(misale.errors.count, "error") %> prohibited this misale from being saved:</h2>
	
	  <ul>
	  <% misale.errors.full_messages.each do |msg| %>
	    <li><%= msg %></li>
	  <% end %>
	  </ul>
	</div>
<% end %>

app/views/misales/_fbPost.html.erb
<input 
type='button' 
class='actionButton' 
value='Post' 
style='background-position: 2px -0px;background-image: url(http://b.static.ak.fbcdn.net/rsrc.php/v1/zz/r/r9ad093yvZ9.png);background-repeat: no-repeat;display: inline-block;padding-left:20px;'
onclick='javascript:window.open(<%= "\"http://www.facebook.com/dialog/feed?app_id=#{ApplicationHelper.FB_APP_ID}&redirect_uri=#{ApplicationHelper.FB_CANVAS}/fbcanvas/?fbpost=#{misale.id}&display=popup&&message=#{misale.name}&link=#{ApplicationHelper.FB_CANVAS}/misales/?page=#{misale.id}&source=#{misale.illustration}\"" %>, "FBPost","height=200,width=580");return false;' />

app/views/misales/_fetan.html.erb
<div id='fetanGameMode'>
<a title='Game mode toggle ON/OFF' href='javascript:toggleFetan()'><%= ApplicationHelper.get_value(:fetan, 'Fetan ') %> <% if @fetan then %><span style="color:green">&#10004;</span><% else %><span style="color:red">&times;</span><% end %></a>
</div>

	
	

app/views/misales/_minishow.html.erb
<div>
	<div align='center' class='itemContent'>
		<div class='misaleheader curvy-five shadow-light-green top-line-bluegreen top-line-bluegreen-ten' misale='<%= misale.head %>'>
			<div class='fetan right'><%= render :partial => 'misales/fetan' %></div>
			<div class='itemid' style='display:none;'>#<%= misale.id %></div>
			<div style='text-align:center;'>
				<span class='geeztext headtext'><%= misale.head %></span>
				<span class='geeztext tailtext questionmark <%= @fetan ? "" : "fetanHidden" %>' misale='<%= misale.head %>' onclick='javascript:revealMisale(this, "fetanHidden", <%= misale.id %>)'>???</span>
				<span id='tail_<%= misale.id %>' class='geeztext tailtext <%= @fetan ? "fetanHidden" : "" %>'><%= misale.tail %></span>
				<br/><br/>
				<% unless misale.illustration.empty? then %>
					<div id='illustration_<%= misale.id %>' class='<%= @fetan ? "illustration fetanHidden" : "illustration" %>'>
						<% if misale.illustration.index('http://www.youtube.com').nil? then %>
							<img width='300px' misale='<%= misale.head %>' align='middle' src='<%= misale.illustration %>' alt='illustration'/>
						<% else %>
							<iframe title="YouTube video player" width="480" height="390" src='<%= misale.illustration %>' frameborder="0" allowfullscreen></iframe>
					 	<% end %>
						<br/>
						<span class='illustrationurl'>source: <%= misale.illustration %></span>
					</div>
				<% end %>
				<div id='share_<%= misale.id %>' class='contentActionLinks'>
					<% if @admin then %>
						<%= link_to ApplicationHelper.get_value(:edit, :edit), edit_misale_path(misale) %>
					<% end %>
					<span class="comment-count-bubble">
						<span onclick='javascript:revealCommentsAndAnswers(<%= misale.id %>)'><%= misale.comments.count + misale.answers.count %></span>
					  	<span class="comment-count-bubble-arrow"></span>
					</span>
					<%= render :partial => 'misales/fbPost', :locals => { :misale => misale } %>
					<%= render :partial => 'misales/tweetThisContent', :locals => { :misale => misale } %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/misales/_search.html.erb
<%= form_tag misales_path, :method => 'get' do %>  
    <%= text_field_tag :search %>  
    <%= submit_tag "Search", :name => nil, :class => :actionButton %> 
<% end %> 

app/views/misales/_sharedshow.html.erb
<p id="notice"><%= notice %></p>

<%= render :partial => 'error', :locals => {:misale => misale} %>

<%= render :partial => "minishow", :locals => { :misale => misale } %>

<div class='misaleBody' >
	<%= render :partial => 'misales/answers', :locals => { :misale => misale } %>
	<br/>
	<%= render :partial => "misales/comment", :locals => { :misale => misale  } %>
</div>

app/views/misales/_showwithcomment.html.erb
<%= render :partial => "minishow", :locals => { :misale => @misale } %>

<p>
	<b>comments:</b>
</p>

<%= simple_form_for(@misale) do |f| %>
	<% f.fields_for :comments do |builder| %>
		<% if builder.object.nickname.nil? %>
			<p>
				<%= builder.input :nickname %>
				<%= builder.input :phone %>
				<%= builder.input :email %>
				<%= builder.input :comment %>
			</p>
		<% else %>
			<p>
				<%= builder.object.nickname %>[<%= builder.object.created_at %>]
			</p>
			<p>
				<%= builder.object.comment %>
			</p>
		<% end %>
	<% end %>
	
	<div class="actions">
		<%= f.button :submit, :value => 'submit' %>
	</div>
<% end %>

app/views/misales/_unload.html.erb
<html>
	<body>
		<script type='text/javascript'>
			window.onload = function() {
			 	window.close();
			};
		</script>
	</body>
</html>

app/views/misales/home.html.erb
   <div>
   		<br/>
      <div>
        <div id="header">
          <h2>Welcome to Ge'ez Chewata</h2>
        </div>

        <div id="getting-started" style='text-align:left;' class='misaleheader curvy-five shadow-light-green top-line-bluegreen top-line-bluegreen-ten'>
		<h2>
			Hey, so how well do you know your language? 
		</h2>
		<h2>
			Have fun recalling some of the constructs...or show off your chops &#x1306;. 
		</h2>
		<h2>
			Start out with "Misaleyawi Anegageroch" - &#x121D;&#x1233;&#x120C;&#x12EB;&#x12CA; &#x12A0;&#x1290;&#x130B;&#x1308;&#x122E;&#x127D;
		</h2>
          <h2>Getting started</h2>
          <ul>
            <li>
            	<h2>
               (<%= ApplicationHelper.get_value(:geez, :geez) %>) - Do you read the word Ge'ez within the brackets? 
			  		<br/> &nbsp;&nbsp;<i>Yes.</i> - Great! You have the font you need.
					<br/> &nbsp;&nbsp;<i>No, I see boxes.</i> - No worries, you are likely missing a Ge'ez font. Get one from <a href='ftp://ftp.ethiopic.org/pub/fonts/TrueType/gfzemenu.ttf' target='_blank'>here</a>.
			  </h2>
            </li>

            <li>
              <h2>Jump in
			  	<br/>&nbsp;&nbsp;<a href='/challenges' class='actionButton curvy-five shadow-light-green top-line-bluegreen'><%= ApplicationHelper.get_value(:challenges, :challenges) %></a> - Fill in the blank type of questions.
				<br/>&nbsp;&nbsp;<a href='/misales' class='actionButton curvy-five shadow-light-green top-line-bluegreen'><%= ApplicationHelper.get_value(:misales, :misales) %></a> - Browse content. Try the game (&#x1328;&#x12CB;&#x1273;) mode. It's fun!
              </h2>
			</li>
          </ul>
		  <fb:login-button show-faces="true" width="200" max-rows="1"></fb:login-button>
        </div>
      </div>

      <div id="footer">
		<br/>
		<br/>
      </div>
    </div>

app/views/misales/index.html.erb
<br/>
<%= will_paginate %>
<br/>
<% @misales.each do |misale| %>
	<%= render :partial => 'sharedshow', :locals => {:misale => misale} %>
<% end %>
<br />

app/views/misales/new.html.erb
<h1>New misale</h1>

<%= render 'form' %>

<%= link_to 'Back', misales_path %>

app/views/misales/show.html.erb
<%= render :partial => 'sharedshow', :locals => {:misale => @misale} %>