config/routes.rb
Misaleanegager::Application.routes.draw do
  resources :contacts

  resources :lookups

  resources :misales

  resources :challenges

  resources :about

  match '/fetan/toggle' => 'application#fetan'
  
  match '/misales/:id/fbpost' => 'misales#fbpost', :as => :fbpost_misale
  
  match '/' => 'misales#home'
  
  match '/fbcanvas' => 'application#fbcanvas'
  
  match '/oqpi' => 'application#tweet'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= raw(ApplicationHelper.APPLICATION_NAME) %></title>
	<meta http-equiv="content-type" content="text/html;charset=UTF-8" />
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'http://platform.twitter.com/widgets.js', 'http://connect.facebook.net/en_US/all.js', 'https://ajax.googleapis.com/ajax/libs/jquery/1.5.0/jquery.min.js', 'https://www.google.com/jsapi?key=ABQIAAAAxL9s1Fj_nPKf1uO3mmsrahTJQa0g3IQ9GZqIMmInSLzwtGDKaBTgu1i2DaKiAVk2NKmUfb01lk8ulw', 'application' %>
  <%= csrf_meta_tag %>
  <script type="text/javascript">
	
	  var _gaq = _gaq || [];
	  _gaq.push(['_setAccount', 'UA-22325015-1']);
	  _gaq.push(['_trackPageview']);
	
	  (function() {
	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	  })();
	
	</script>
  </head>
  <body>
    <div id="page">
      <div>
        <div style='clear:both;border-bottom:3px solid #EE2B76;height:30px;'>
	    	<div class='navmenu'>
				<a href="/"><span class="logo logo_1" style="float:left;"></span></a>
				<div class='navmenuitem curvy-five'><%= link_to ApplicationHelper.get_value(:misales, 'Misales') , misales_path %></div>
				<div class='navmenuitem curvy-five'><%= link_to ApplicationHelper.get_value(:challenges, 'Challenges'), challenges_path %></div>
			</div>
			<div class='search'>
				<%= render :partial => 'misales/search' %>
			</div>
        </div>
		<div class='utillinks'>
			<input id='btn_faq' type='button' style='float:right;font-weight:bold' class='faq' onclick='javascript:window.open("/faq.html", "FAQ","height=400,width=800")' value='?'/>
			<a href='#' onclick='javascript:inviteFriends()' style='float:right'>invite friends</a>
		</div>
		<iframe src="http://www.facebook.com/plugins/like.php?href=<%= ApplicationHelper.FB_CANVAS %>&amp;layout=button_count&amp;show_faces=false&amp;width=450&amp;action=like&amp;font=tahoma&amp;colorscheme=light&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; width:450px; height:21px;" allowTransparency="true"></iframe>
		<div id='inlineAlert' style='display:none;'></div>
		<div style='clear:both;'>
			<%= yield %>
		</div>
         
      </div>

      <div id="footer">
  	      
      </div>
      <div id="fb-root"></div>
    </div>
  </body>
</html>